### ISSUE TITLE
Update documents and containers about Julia & REST plugin

### ISSUE THREAD

**Issue by cissieAB** [nathanwbrei/phasm#37]
Nathan initialized the Julia plugin in https://github.com/nathanwbrei/phasm/commit/0899a904c79b387e914b726f34c6fde7633ced56, which is a great progress to meet the milestones.

- [x] The commit lead to changes of the original compiling and building process. Thus the documentation has to be updated correspondingly.
- [x] It brings Julia onto table, we need to go through the process and build containers with Julia. To make things easier, we can start with Julia and libtorch_cpu only, ignoring pin, dwarf etc.

**Comment by nathanwbrei** [comment]
I just merged the branch nbrei_dep_handling, which takes care of item 2. Two new containers are added, `phasm_dev_env` and `phasm_cuda_env`. They include Julia and Geant4, and you can download them from docker hub via:

```bash
docker pull nbrei/phasm_dev_env:latest
```

In theory, libtorch_cpu and libtorch_cuda are no longer necessary, but I'm not going to delete them until we are confident that phasm_dev_env and phasm_cuda_env fully replace them. 

There are several main improvements: 

1. The new Dockerfile has args `USE_JULIA`, `USE_GEANT4`, etc, that exactly match the CMake flags. This means that you can build a lighter container that omits dependencies you know you won't need without creating a new Dockerfile. 

2. All logic for downloading, installing system libraries, building, and installing dependencies has moved into the `scripts` directory. Each script is similarly controlled by the same `USE_JULIA`, etc, flags. These scripts can be run from the Dockerfile, or externally. This means you can use the same script if you aren't using containers at all, or are putting your dependencies on cvmfs and bind-mounting them instead of baking them into the Docker container.

3. Downloading is done _outside_ of the Dockerfile. This solves three problems we've been having. Firstly, a lot fewer headaches with JLab certificates. Secondly, faster Docker builds, since Docker is unreliable about caching the download the first time around. Thirdly, having fewer Docker layers means less dramatic disk space leaks, which means fewer failed Docker builds.
