### ISSUE TITLE
Docker container needs to lock down dependencies

### ISSUE THREAD

**Issue by nathanwbrei** [nathanwbrei/phasm#8]
Right now, there is a docker container, but it has some problems:
1. It is based on CentOS7, which has an obsolete compiler and unusable system libraries. The main ML frameworks all strongly prefer Ubuntu.
2. The docker container doesn't lock in a working version of the PHASM dependencies. The user has to manually install dependencies via download_deps.sh, which
    - Currently has an error because it doesn't pin the JANA release
    - Doesn't play nicely with IDEs
    - Leads to us having to re-download and reconfigure the dependencies weirdly often
3. Getting the Intel PIN components to compile alongside the others still has problems. We need to be able to get all of PHASM to compile simultaneously on at least one architecture. 
4. For the Q1 milestone, we need to add llvm and ROSE as optional dependencies. These are both quite heavy.

**Comment by nathanwbrei** [comment]
It looks like Cissie and I have both made a lot of progress on this, see PR #12. We decided to use ` nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04` as the base for the Docker and Singularity containers and **only** support the linux+CUDA version of pytorch for now. The final missing piece is getting the llvm/clang and ROSE dependencies into a Docker container as well.

**Comment by cissieAB** [comment]
In short, my situation is that we can build the nvidia-cuda docker container on MacOS, but PHASM would not compile within the container on MacOS.

Hi, @nathanwbrei I tried again and again, to compile PHASM inside the nvidia-cuda container (either based on libtorch_cpu or libtorch_cu) on my Macbook. It was not only slow, it actually got stuck every time at ~50% of the building process, and would not move on for hours so that I had to kill it manually.

Thus I wonder if we can run the nvidia-cuda container on a macOS. I see this post (https://github.com/NVIDIA/nvidia-docker/issues/101) says the users cannot use nvidia-docker on macOS and recent cuda container failed on macOS.

If that is the case, what's our plan?

**Comment by nathanwbrei** [comment]
It could be an M1 issue. Did you try it using my container (which uses the same base image but apparently the wrong pytorch?) Since we are most likely never going to call an NVIDIA GPU from macOS anyhow, we can maintain a separate (lighter) Dockerfile for macos. We can set up two plugin backends, one which uses the CUDA pytorch, and one which uses the non-CUDA pytorch. (That way we don't have to do too much preprocessor macro nonsense)

**Comment by cissieAB** [comment]
I closed PR #12 which only has a libtorch_cuda dockerfile. 

Separate ubuntu:latest and macos-latest docker containers will be provided.
